application:
  security:
    jwt:
      secret-key: "66546A576E5A7234753778214125442A472D4B6150645367566B587032733576"
      expiration: 86400000  # 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pazaruvalnik?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect



