

application:
  security:
    jwt:
      secret-key: "66546A576E5A7234753778214125442A472D4B6150645367566B587032733576"
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

